### ISSUE TITLE
Impossible to set `jinja2.i18n.gettext` via configuration file

### ISSUE THREAD

**Issue by amirouche** [Pylons/pyramid_jinja2#122]
On Python3, using pyramid_jinja2 2.5, while setting `jinja2.i18n.gettext` I hit the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyramid/config/__init__.py", line 1059, in execute_actions
    callable(*args, **kw)
  File "/usr/lib/python3/dist-packages/pyramid_jinja2/__init__.py", line 440, in register
    package,
  File "/usr/lib/python3/dist-packages/pyramid_jinja2/settings.py", line 134, in parse_env_options_from_settings
    if not issubclass(gettext_wrapper, GetTextWrapper):
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pserve3", line 9, in <module>
    load_entry_point('pyramid==1.5.1', 'console_scripts', 'pserve')()
  File "/usr/lib/python3/dist-packages/pyramid/scripts/pserve.py", line 51, in main
    return command.run()
  File "/usr/lib/python3/dist-packages/pyramid/scripts/pserve.py", line 316, in run
    global_conf=vars)
  File "/usr/lib/python3/dist-packages/pyramid/scripts/pserve.py", line 340, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python3/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/opt/olfeo/lib/python3.4/site-packages/stats_gui/main.py", line 56, in main
    return config.make_wsgi_app()
  File "/usr/lib/python3/dist-packages/pyramid/config/__init__.py", line 939, in make_wsgi_app
    self.commit()
  File "/usr/lib/python3/dist-packages/pyramid/config/__init__.py", line 610, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/usr/lib/python3/dist-packages/pyramid/config/__init__.py", line 1067, in execute_actions
    tb)
  File "/usr/lib/python3/dist-packages/pyramid/compat.py", line 131, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/pyramid/config/__init__.py", line 1059, in execute_actions
    callable(*args, **kw)
  File "/usr/lib/python3/dist-packages/pyramid_jinja2/__init__.py", line 440, in register
    package,
  File "/usr/lib/python3/dist-packages/pyramid_jinja2/settings.py", line 134, in parse_env_options_from_settings
    if not issubclass(gettext_wrapper, GetTextWrapper):
pyramid.exceptions.ConfigurationExecutionError: <class 'TypeError'>: issubclass() arg 1 must be a class
  in:
  Line 482 of file /usr/lib/python3/dist-packages/pyramid_jinja2/__init__.py:
    config.add_jinja2_renderer('.jinja2', package=package)
```

I think this is a bug. I am willing to help. Meanwhile can someone provide a wordaround?

Thanks

**Comment by mmerickel** [comment]
It would help if you pasted the code/configuration that was triggering this error.

**Comment by mmerickel** [comment]
a) This is a bug, If you wanted to fix it the PR should be quite simple to make.
b) A workaround for now is to pass the object at runtime instead of from the config file via `settings['jinja2.i18n.gettext'] = my_gettext_wrapper` instead of passing a string.

**Comment by amirouche** [comment]
Here is the configuration:

```ini
[app:main]
use = call:stats_gui.main:main

pyramid.includes =
	pyramid_jinja2
scss.asset_path = stats_gui:assets/scss
scss.compress = true
scss.cache = true
pyramid.default_locale_name = en
available_languages = fr en
jinja2.i18n.gettext = 


[server:main]
use = egg:pyramid#wsgiref
host = 0.0.0.0
port = 6543
```

**Comment by amirouche** [comment]
> b) A workaround for now is to pass the object at runtime instead of from the config file via settings['jinja2.i18n.gettext'] = my_gettext_wrapper instead of passing a string.

But how? I don't know how to add pyramid_jinja2 to a project configuration without using the config file.

**Comment by mmerickel** [comment]
You're passing an empty string for `jinja2.i18n.gettext` ?

**Comment by mmerickel** [comment]
You pass the settings to pyramid... `config = Configurator(settings=settings)` right? You can change and add settings before doing that.

**Comment by amirouche** [comment]
> You're passing an empty string for jinja2.i18n.gettext ?

no i pass `foo.bar.baz`, if fixed the example code.

> You pass the settings to pyramid...

Thanks.
